volumes:
  chat_src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./app/src/app
  api_src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./api/src/api
  shared:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./shared

networks:
  internal:
    driver: bridge
  services_net_postgres:
    external: true
  services_net_redis:
    external: true

services:
  chat:
    container_name: terra_chat
    image: terra_chat:latest
    build:
      context: ./
      dockerfile: ./app/src/Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - 8501:8501
    depends_on:
      - api
    volumes:
      - chat_src:/app/app
      - shared:/shared
    networks:
      - internal
  
  api:
    container_name: terra_api
    image: terra_api:latest
    build:
      context: ./
      dockerfile: ./api/src/Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - api_src:/api
      - shared:/shared
    networks:
      - internal
      - services_net_postgres
      - services_net_redis
    extends:
      file: ./services.${ENV}.yaml
      service: api
    