volumes:
  jobs_src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./jobs/src/jobs
  shared:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./shared

networks:
  services_net_postgres:
    external: true
  services_net_redis:
    external: true

services:
  jobs:
    container_name: terra_jobs
    image: terra_jobs:latest
    build:
      context: ./jobs
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - jobs_src:/src/jobs
      - shared:/src/shared
    networks:
      - internal
      - services_net_postgres
      - services_net_redis