networks:
  internal:
    driver: bridge
  services_net_postgres:
    external: true
  services_net_redis:
    external: true

volumes:
  podcast_audio:
    driver: local
    driver_opts:
      type: none
      device: ${PODCAST_AUDIO_DIR}
      o: bind

services:
  app:
    container_name: terra_app
    image: terra_app:latest
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - 8501:8501
    depends_on:
      - api
    networks:
      - internal
    volumes:
      - podcast_audio:/etc/terra/podcast_audio
  
  api:
    container_name: terra_api
    image: terra_api:latest
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    env_file:
      - ./.env
    networks:
      - internal
      - services_net_postgres
      - services_net_redis
    volumes:
      - podcast_audio:/etc/terra/podcast_audio
    extends:
      file: ./services.${ENV}.yaml
      service: api