networks:
  internal:
    driver: bridge
  services_net_postgres:
    external: true
  services_net_redis:
    external: true

services:
  app:
    container_name: terra_app
    image: terra_app:latest
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - 8501:8501
    depends_on:
      - api
    networks:
      - internal
  
  api:
    container_name: terra_api
    image: terra_api:latest
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    env_file:
      - ./.env
    networks:
      - internal
      - services_net_postgres
      - services_net_redis
    extends:
      file: ./services.${ENV}.yaml
      service: api