[tool.uv]
dev-dependencies = [
    "ruff>=0.6.1",
]

[tool.uv.workspace]
members = ["api", "app", "shared", "jobs"]

[tool.uv.sources]
shared = { workspace = true }

[tool.ruff]
line-length = 88
fix = true

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "ASYNC",
    "N",
    "UP",
    "YTT",
    "DTZ",
    "A",
    "B",
    "I"
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = true
