services:
  streamlit:
    build: .
    environment:
      - AUTH_USERS=${AUTH_USERS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIRECT_URI=${REDIRECT_URI}
    ports:
      - '8501:8501'
    depends_on:
      - ollama
  
  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    ports:
      - 11434:11434
    volumes:
      - ${MODELS_PATH}:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]