services:
  streamlit:
    build: .
    ports:
      - '8501:8501'
    depends_on:
      - ollama
      - postgres
  
  ollama:
    volumes:
      - ${MODELS_PATH}:/root/.ollama
    extends:
      file: ../svc/services.${ENV}.yaml
      service: ollama
    
  postgres:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    extends:
      file: ../svc/services.${ENV}.yaml
      service: postgres