services:
  terrachat:
    build: .
    ports:
      - '8501:8501'
    depends_on:
      - ollama
      - postgres
  
  ollama:
    volumes:
      - ${MODELS_PATH}:/root/.ollama
    extends:
      file: ../svc/services.${ENV}.yaml
      service: ollama
    
  postgres:
    extends:
      file: ../svc/services.${ENV}.yaml
      service: postgres