  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    ports:
      - 11434:11434
    volumes:
      - ${MODELS_PATH}:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0