services:
  streamlit:
    build: .
    ports:
      - '8501:8501'
    depends_on:
      - ollama
      - postgres
  
  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    ports:
      - 11434:11434
    volumes:
      - ${MODELS_PATH}:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    restart: unless-stopped