[project]
name = "terra_app"
version = "1.0.0"
description = "Web UI for the Terra App"
requires-python = ">=3.12.4"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]