volumes:
  jobs_src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src/jobs

networks:
  services_net_postgres:
    external: true
  services_net_redis:
    external: true

services:
  jobs:
    container_name: terra_jobs
    image: terra_jobs:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - jobs_src:/src/jobs
    networks:
      - services_net_postgres
      - services_net_redis