[project]
name = "terra_shared"
version = "0.1.0"
description = "Shared Resources for the Terra project"
requires-python = ">=3.12.4"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["shared"]