name: Deploy App

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - "api/**"
      - "shared/**"
      - "compose.yaml"
      - "services.*.yaml"
      - ".github/workflows/deploy_app.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Push App Files
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        source: "app/*"
        target: "terra_app"

    - name: Push API Files
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        source: "api/*"
        target: "terra_app"
    
    - name: Push Shared Files
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        source: "shared/*"
        target: "terra_app"
    
    - name: Push Docker Files
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        source: "compose.yaml, services.*.yaml"
        target: "terra_app"
    
    - name: Restart Docker Containers
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        script: |
          cd terra_app
          docker-compose down
          docker-compose up --build -d