name: Deploy App

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Push Files
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        source: "app/*"
        target: "terra"

  # deploy_services:
  #   runs-on: ubuntu-latest
  #   environment: production

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
    
  #   - name: Deploy Files
  #     uses: appleboy/scp-action@v0.1.3
  #     with:
  #       host: ${{ secrets.HOST_ADDRESS }}
  #       username: ${{ secrets.HOST_USERNAME }}
  #       key: ${{ secrets.HOST_SSH_KEY }}
  #       source: "svc/*"
  #       target: "terra"
  
    
    # - name: Rebuild Docker Images
    #   uses: appleboy/ssh-action@v0.1.3
    #   with:
    #     host: ${{ secrets.HOST_ADDRESS }}
    #     username: ${{ secrets.HOST_USERNAME }}
    #     key: ${{ secrets.HOST_SSH_KEY }}
    #     script: |
    #       cd terra/app
    #       docker-compose down
    #       docker-compose -f compose.yaml up --build -d
