name: Deploy Jobs

on:
  push:
    branches: [ "main" ]
    paths:
      - "jobs/**"
      - "compose.jobs.yaml"
      - ".github/workflows/deploy_jobs.yml"
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Push Files
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        source: "jobs/*, compose.jobs.yaml"
        target: "terra"
  
    - name: Restart Docker Container
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        script: |
          cd terra
          docker-compose -f compose.jobs.yaml down
          docker-compose -f compose.jobs.yaml up --build -d