name: Deploy API

on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Push Files
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        source: "api/*"
        target: "terra"