name: Deploy Terra Chat App

on:
  workflow_run:
    workflows: ["Deploy Terra Services"]
    types:
      - completed
  push:
    branches: [ "main" ]
    paths:
      - "app/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Deploy Files
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        source: "app/*"
        target: "terra"
    
    - name: Rebuild Docker Images
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSH_KEY }}
        script: |
          cd terra/app
          docker-compose down
          docker-compose -f compose.yaml up --build -d
